# Mini Project 2- Exploring AI Use by Demographic Features

## Using Dataset: Pew Research ATP W152, August 2024

In [2]:
import pandas as pd
import numpy as np

## Include ATP W152- August 2024 Dataset

In [3]:
data = pd.read_csv('data/August 2024/ATP W152.csv')

In [4]:
display(data.describe())
display(data.head())
data.columns()

,QKEY,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,AICONTROL1_W152,AICONTROL2_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
count,5.410000e+03,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.00000,5410.000000,5410.000000,5410.000000,...,2365.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000
mean,1.869364e+11,1.688725,1.039741,9.023660,1.500739,1.913124,2.82902,4.211460,4.131423,2.363216,...,9.648626,1.797597,2.782810,1.412754,10.103327,4.836969,2.125508,2.201664,7.882625,1.000000
std,5.318192e+10,0.960277,0.195369,0.152001,0.500046,5.480991,7.33057,7.546541,7.155505,5.464507,...,26.944175,1.483587,1.794066,0.767634,20.203061,13.480087,6.403944,6.997570,23.273008,0.595664
min,1.003140e+05,1.000000,1.000000,9.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.135260
25%,2.018011e+11,1.000000,1.000000,9.000000,1.000000,1.000000,2.00000,2.000000,3.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000,1.000000,1.000000,0.685758
50%,2.020010e+11,1.000000,1.000000,9.000000,2.000000,2.000000,2.00000,4.000000,4.000000,2.000000,...,2.000000,2.000000,3.000000,1.000000,6.000000,3.000000,2.000000,2.000000,2.000000,0.907527
75%,2.024000e+11,3.000000,1.000000,9.000000,2.000000,2.000000,3.00000,5.000000,4.000000,2.000000,...,2.000000,2.000000,4.000000,1.000000,9.000000,4.000000,2.000000,2.000000,3.000000,1.161045
max,2.024000e+11,4.000000,2.000000,10.000000,2.000000,99.000000,99.00000,99.000000,99.000000,99.000000,...,99.000000,9.000000,9.000000,3.000000,99.000000,99.000000,99.000000,99.000000,99.000000,3.737946

,QKEY,INTERVIEW_START_W152,INTERVIEW_END_W152,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
0,100314,15-Aug-2024 15:30:49,15-Aug-2024 15:40:52,1,1,9,1,2,2,5,...,NaN,1,2,1,7,3,3,1,2,0.639769
1,103379,15-Aug-2024 13:58:04,15-Aug-2024 14:21:23,3,1,9,1,2,2,5,...,NaN,1,1,1,9,2,5,2,3,1.338840
2,104727,15-Aug-2024 07:18:22,15-Aug-2024 07:24:47,1,1,9,2,2,3,5,...,NaN,1,1,1,99,2,2,2,99,0.909360
3,106590,13-Aug-2024 22:30:51,13-Aug-2024 22:36:57,1,1,9,1,2,2,5,...,1.0,1,2,1,8,3,2,1,2,0.919896
4,107668,13-Aug-2024 15:23:41,13-Aug-2024 15:30:23,1,1,9,2,2,2,3,...,1.0,1,2,1,9,3,1,1,3,0.719993

TypeError: 'Index' object is not callable

In [ ]:
for i in data.columns.to_list():
    print(i)

In [ ]:
data.drop_duplicates(inplace=True)
data.dropna(how='all', inplace=True)

## Subset for Regression Models
- `QKEY` is the unique identifier (id) per row
- Including predictor and outcome variables planned for logit and ols models
- Outcome variables: 
    - `CHATUSE_W152` is binary (coded 1, 2) for logit
    - `USEAI_W152` is likert for ols

In [ ]:
predictor_cols = ['F_INC_SDT1', 'F_EDUCCAT', 'F_AGECAT', 'F_GENDER', 'F_RACECMB', 'F_RACETHNMOD']
outcome_cols = ['CHATUSE_W152', 'USEAI_W152']
include_cols = ['QKEY'] + predictor_cols + outcome_cols
data = data[include_cols]
data.head(20)

## Recode Variables

In [ ]:
# 99 = "Refused" code; recode as missing
recode_99_cols = predictor_cols + outcome_cols
for col in recode_99_cols:
    data[col] = data[col].replace(99, np.nan)

# Remap Binary Outcome Variable
data['CHATUSE_W152'] = data['CHATUSE_W152'].replace({2: 0})  # 1 = Yes, have used, 0 = No, have not used

display(data.describe())
display(data.head(20))

In [ ]:
# Save cleaned/recoded data for regression analysis
data.to_csv('data/August 2024/atp-w152-clean.csv', index=False)

# Ordinal Logistic Regression

In [ ]:
data.isna().sum() # Categorical ChatUse has 25% missing data, which seems quiet a lot, so not sure we should just drop NaNs, but I did it anyways LOL

In [ ]:
data = data.dropna()
data.describe()

## Logistic Regression

In [ ]:
import statsmodels.api as sm
import statsmodels.formula.api as smf

np.random.seed(42)

X = data[['F_INC_SDT1','F_EDUCCAT','F_AGECAT','F_GENDER','F_RACECMB']]
y = data["CHATUSE_W152"]

X = sm.add_constant(X)

logreg = sm.Logit(y, X)
logreg_results = model.fit()

In [ ]:
print(logreg_results.summary()) # the regular table is not very intepretable because of log odds

In [ ]:
df_odds = logreg_results.conf_int()
df_odds["Odds Ratio"] = logreg_results.params
df_odds.columns = ["CI lower", "CI Upper", "Odds Ratio"]

# converting from log odds to odds ratios for intepretabiliy
df_odds = np.exp(df_odds)

# percent change
df_odds["% Change"] = (df_odds["Odds Ratio"] - 1) * 100

# CI effect
conditions = [
    (df_odds["CI lower"] > 1.0) & (df_odds["CI Upper"] > 1.0),  # Entirely above 1
    (df_odds["CI lower"] < 1.0) & (df_odds["CI Upper"] < 1.0),  # Entirely below 1
]
choices = ["Positive Effect", "Negative Effect"]
df_odds["CI Effect"] = np.select(conditions, choices, default="No Effect")

# P-value
df_odds["P-value"] = logreg_results.pvalues
df_odds["Significant"] = df_odds["P-value"] < 0.05

df_odds = df_odds[["Odds Ratio","% Change","CI lower","CI Upper","CI Effect","P-value","Significant"]]

df_odds

## Interpretation

### Income
As CI bounds are above 1.0, income has a positive effect on AI usage. The result is significant (p < 0.05). With one unit increase in income, the odds of using AI increase by 8.35%. 

### Education
As CI bounds are below 1.0, education has a negative effect on AI usage. The result is significant (p < 0.05). With one unit increase in education, the odds of using AI decrease by 37.66%. 

### Age
As CI bounds are below 1.0, age has a negative effect on AI usage. The result is significant (p < 0.05). With one unit increase in age, the odds of using AI decrease by 48.62%. The baseline age is 18 years old though.