# Mini Project 2- Exploring AI Use by Demographic Features

## Using Dataset: Pew Research ATP W152, August 2024

In [17]:
import pandas as pd
import numpy as np

## Include ATP W152- August 2024 Dataset

In [18]:
data = pd.read_csv('data/August 2024/ATP W152.csv')

In [19]:
display(data.describe())
display(data.head())

,QKEY,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,AICONTROL1_W152,AICONTROL2_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
count,5.410000e+03,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.00000,5410.000000,5410.000000,5410.000000,...,2365.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000
mean,1.869364e+11,1.688725,1.039741,9.023660,1.500739,1.913124,2.82902,4.211460,4.131423,2.363216,...,9.648626,1.797597,2.782810,1.412754,10.103327,4.836969,2.125508,2.201664,7.882625,1.000000
std,5.318192e+10,0.960277,0.195369,0.152001,0.500046,5.480991,7.33057,7.546541,7.155505,5.464507,...,26.944175,1.483587,1.794066,0.767634,20.203061,13.480087,6.403944,6.997570,23.273008,0.595664
min,1.003140e+05,1.000000,1.000000,9.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.135260
25%,2.018011e+11,1.000000,1.000000,9.000000,1.000000,1.000000,2.00000,2.000000,3.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000,1.000000,1.000000,0.685758
50%,2.020010e+11,1.000000,1.000000,9.000000,2.000000,2.000000,2.00000,4.000000,4.000000,2.000000,...,2.000000,2.000000,3.000000,1.000000,6.000000,3.000000,2.000000,2.000000,2.000000,0.907527
75%,2.024000e+11,3.000000,1.000000,9.000000,2.000000,2.000000,3.00000,5.000000,4.000000,2.000000,...,2.000000,2.000000,4.000000,1.000000,9.000000,4.000000,2.000000,2.000000,3.000000,1.161045
max,2.024000e+11,4.000000,2.000000,10.000000,2.000000,99.000000,99.00000,99.000000,99.000000,99.000000,...,99.000000,9.000000,9.000000,3.000000,99.000000,99.000000,99.000000,99.000000,99.000000,3.737946

,QKEY,INTERVIEW_START_W152,INTERVIEW_END_W152,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
0,100314,15-Aug-2024 15:30:49,15-Aug-2024 15:40:52,1,1,9,1,2,2,5,...,NaN,1,2,1,7,3,3,1,2,0.639769
1,103379,15-Aug-2024 13:58:04,15-Aug-2024 14:21:23,3,1,9,1,2,2,5,...,NaN,1,1,1,9,2,5,2,3,1.338840
2,104727,15-Aug-2024 07:18:22,15-Aug-2024 07:24:47,1,1,9,2,2,3,5,...,NaN,1,1,1,99,2,2,2,99,0.909360
3,106590,13-Aug-2024 22:30:51,13-Aug-2024 22:36:57,1,1,9,1,2,2,5,...,1.0,1,2,1,8,3,2,1,2,0.919896
4,107668,13-Aug-2024 15:23:41,13-Aug-2024 15:30:23,1,1,9,2,2,2,3,...,1.0,1,2,1,9,3,1,1,3,0.719993

In [20]:
for i in data.columns.to_list():
    print(i)

QKEY
INTERVIEW_START_W152
INTERVIEW_END_W152
DEVICE_TYPE_W152
SVYMODE_W152
LANG_W152
FORM_W152
AI_HEARD_W152
CNCEXC_W152
USEAI_W152
AICONTROL1_W152
AICONTROL2_W152
AICHANGE_W152
AIFUTRIMPCT_a_W152
AIFUTRIMPCT_b_W152
AIFUTRIMPCT_c_W152
AIFUTRIMPCT_d_W152
AIFUTRIMPCT_e_W152
AIFUTRIMPCT_f_W152
AIFUTRIMPCT_g_W152
AIFUTRIMPCT_h_W152
AIFUTRIMPCT_i_W152
AIFUTRIMPCT_j_W152
AIJOBS_W152
AIJOBIMPCT_a_W152
AIJOBIMPCT_b_W152
AIJOBIMPCT_c_W152
AIJOBIMPCT_d_W152
AIJOBIMPCT_e_W152
AIJOBIMPCT_f_W152
AIJOBIMPCT_g_W152
AIJOBIMPCT_h_W152
AIJOBIMPCT_i_W152
AIJOBIMPCT_j_W152
HUMANVAI_a_W152
HUMANVAI_b_W152
HUMANVAI_c_W152
HUMANVAI_d_W152
HUMANVAI_e_W152
HUMANVAI_f_W152
HUMANVAI_g_W152
HUMANVAI_h_W152
PERSBENHRM_W152
TRSTAIPRS_W152
AICONCERN_a_W152
AICONCERN_b_W152
AICONCERN_c_W152
AICONCERN_d_W152
AICONCERN_e_W152
AICONCERN_f_W152
AICONCERN_g_W152
FUTRAI_a_W152
FUTRAI_b_W152
FUTRAI_c_W152
FUTRAI_d_W152
DISCRIM1_a_W152
DISCRIM1_b_W152
DISCRIM1_c_W152
DISCRIM1_d_W152
DISCRIM1_e_W152
DISCRIM1_f_W152
AIREG_W152
REGCONFG_W152
REGCONFI_W152
CHATAWARE_W152
CHATUSE_W152
CHATHELPFUL_W152
DRIVE1_W152
DRIVE2_a_W152
DRIVE2_b_W152
DRIVE2_c_W152
DRIVE2_d_W152
DRIVE2_e_W152
DRIVE2_f_W152
DRIVE3_W152
DRIVER_W152
F_METRO
F_CREGION
F_CDIVISION
F_USR_SELFID
F_AGECAT
F_GENDER
F_EDUCCAT
F_EDUCCAT2
F_HISP
F_HISP_ORIGIN
F_YEARSINUS_RECODE
F_RACECMB
F_RACETHNMOD
F_BIRTHPLACE
F_MARITAL
F_RELIG
F_BORN
F_RELIGCAT1
F_ATTENDPER
F_PARTY_FINAL
F_PARTYLN_FINAL
F_PARTYSUM_FINAL
F_PARTYSUMIDEO_FINAL
F_REG
F_INC_SDT1
F_IDEO
F_INTFREQ
F_VOLSUM
F_INC_TIER2
WEIGHT_W152

In [21]:
data.drop_duplicates(inplace=True)
data.dropna(how='all', inplace=True)

## Subset for Regression Models
- `QKEY` is the unique identifier (id) per row
- Including predictor and outcome variables planned for logit and ols models
- Outcome variables: 
    - `CHATUSE_W152` is binary (coded 1, 2) for logit
    - `USEAI_W152` is likert for ols

In [22]:
predictor_cols = ['F_INC_SDT1', 'F_EDUCCAT', 'F_AGECAT', 'F_GENDER', 'F_RACECMB', 'F_RACETHNMOD']
outcome_cols = ['CHATUSE_W152', 'USEAI_W152']
include_cols = ['QKEY'] + predictor_cols + outcome_cols
data = data[include_cols]
data.head(20)

,QKEY,F_INC_SDT1,F_EDUCCAT,F_AGECAT,F_GENDER,F_RACECMB,F_RACETHNMOD,CHATUSE_W152,USEAI_W152
0,100314,7,2,4,1,1,1,NaN,5
1,103379,9,2,4,1,1,1,NaN,5
2,104727,99,3,3,1,1,1,NaN,5
3,106590,8,1,3,2,1,1,NaN,5
4,107668,9,1,3,2,1,1,2.0,3
5,108435,9,1,4,2,1,1,2.0,2
6,108592,5,2,4,2,2,2,2.0,3
7,112238,6,3,4,2,1,1,NaN,5
8,112371,3,2,3,2,1,3,2.0,5
9,116422,5,3,4,2,1,1,NaN,5
10,116591,2,3,4,2,1,1,NaN,5
11,118110,99,3,3,2,1,1,NaN,5
12,118218,3,2,4,2,1,1,2.0,2
13,126211,2,3,4,1,1,1,2.0,2
14,127160,5,1,2,2,5,4,2.0,5
15,127284,6,2,3,2,1,1,2.0,2
16,133700,2,3,4,2,1,1,NaN,5
17,144736,9,1,3,2,1,1,1.0,2
18,145364,9,3,3,1,1,1,2.0,2
19,145447,9,1,4,2,1,1,1.0,4

## Recode Variables

In [26]:
# 99 = "Refused" code; recode as missing
recode_99_cols = predictor_cols + outcome_cols
for col in recode_99_cols:
    data[col] = data[col].replace(99, np.nan)

# Remap Binary Outcome Variable
data['CHATUSE_W152'] = data['CHATUSE_W152'].map({1: 1, 2: 0})  # 1 = Yes, have used, 0 = No, have not used

display(data.describe())
display(data.head(20))

,QKEY,F_INC_SDT1,F_EDUCCAT,F_AGECAT,F_GENDER,F_RACECMB,F_RACETHNMOD,CHATUSE_W152,USEAI_W152
count,5.410000e+03,5150.000000,5397.000000,5383.000000,5387.000000,5327.000000,5364.000000,2003.0,5377.000000
mean,1.869364e+11,5.615340,1.842320,2.625859,1.506590,1.631312,1.960291,1.0,3.629719
std,5.318192e+10,3.095709,0.820513,1.017907,0.511385,1.091040,1.348927,0.0,1.344893
min,1.003140e+05,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000
25%,2.018011e+11,3.000000,1.000000,2.000000,1.000000,1.000000,1.000000,1.0,2.000000
50%,2.020010e+11,6.000000,2.000000,3.000000,2.000000,1.000000,1.000000,1.0,4.000000
75%,2.024000e+11,9.000000,3.000000,4.000000,2.000000,2.000000,3.000000,1.0,5.000000
max,2.024000e+11,9.000000,3.000000,4.000000,3.000000,5.000000,5.000000,1.0,5.000000

,QKEY,F_INC_SDT1,F_EDUCCAT,F_AGECAT,F_GENDER,F_RACECMB,F_RACETHNMOD,CHATUSE_W152,USEAI_W152
0,100314,7.0,2.0,4.0,1.0,1.0,1.0,NaN,5.0
1,103379,9.0,2.0,4.0,1.0,1.0,1.0,NaN,5.0
2,104727,NaN,3.0,3.0,1.0,1.0,1.0,NaN,5.0
3,106590,8.0,1.0,3.0,2.0,1.0,1.0,NaN,5.0
4,107668,9.0,1.0,3.0,2.0,1.0,1.0,NaN,3.0
5,108435,9.0,1.0,4.0,2.0,1.0,1.0,NaN,2.0
6,108592,5.0,2.0,4.0,2.0,2.0,2.0,NaN,3.0
7,112238,6.0,3.0,4.0,2.0,1.0,1.0,NaN,5.0
8,112371,3.0,2.0,3.0,2.0,1.0,3.0,NaN,5.0
9,116422,5.0,3.0,4.0,2.0,1.0,1.0,NaN,5.0
10,116591,2.0,3.0,4.0,2.0,1.0,1.0,NaN,5.0
11,118110,NaN,3.0,3.0,2.0,1.0,1.0,NaN,5.0
12,118218,3.0,2.0,4.0,2.0,1.0,1.0,NaN,2.0
13,126211,2.0,3.0,4.0,1.0,1.0,1.0,NaN,2.0
14,127160,5.0,1.0,2.0,2.0,5.0,4.0,NaN,5.0
15,127284,6.0,2.0,3.0,2.0,1.0,1.0,NaN,2.0
16,133700,2.0,3.0,4.0,2.0,1.0,1.0,NaN,5.0
17,144736,9.0,1.0,3.0,2.0,1.0,1.0,1.0,2.0
18,145364,9.0,3.0,3.0,1.0,1.0,1.0,NaN,2.0
19,145447,9.0,1.0,4.0,2.0,1.0,1.0,1.0,4.0