In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

## old dataset

In [2]:
data = pd.read_csv('data/August 2024/ATP W152.csv')

In [4]:
display(data.describe())
display(data.head())

,QKEY,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,AICONTROL1_W152,AICONTROL2_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
count,5.410000e+03,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.00000,5410.000000,5410.000000,5410.000000,...,2365.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000,5410.000000
mean,1.869364e+11,1.688725,1.039741,9.023660,1.500739,1.913124,2.82902,4.211460,4.131423,2.363216,...,9.648626,1.797597,2.782810,1.412754,10.103327,4.836969,2.125508,2.201664,7.882625,1.000000
std,5.318192e+10,0.960277,0.195369,0.152001,0.500046,5.480991,7.33057,7.546541,7.155505,5.464507,...,26.944175,1.483587,1.794066,0.767634,20.203061,13.480087,6.403944,6.997570,23.273008,0.595664
min,1.003140e+05,1.000000,1.000000,9.000000,1.000000,1.000000,1.00000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,0.135260
25%,2.018011e+11,1.000000,1.000000,9.000000,1.000000,1.000000,2.00000,2.000000,3.000000,2.000000,...,1.000000,1.000000,1.000000,1.000000,3.000000,2.000000,1.000000,1.000000,1.000000,0.685758
50%,2.020010e+11,1.000000,1.000000,9.000000,2.000000,2.000000,2.00000,4.000000,4.000000,2.000000,...,2.000000,2.000000,3.000000,1.000000,6.000000,3.000000,2.000000,2.000000,2.000000,0.907527
75%,2.024000e+11,3.000000,1.000000,9.000000,2.000000,2.000000,3.00000,5.000000,4.000000,2.000000,...,2.000000,2.000000,4.000000,1.000000,9.000000,4.000000,2.000000,2.000000,3.000000,1.161045
max,2.024000e+11,4.000000,2.000000,10.000000,2.000000,99.000000,99.00000,99.000000,99.000000,99.000000,...,99.000000,9.000000,9.000000,3.000000,99.000000,99.000000,99.000000,99.000000,99.000000,3.737946

,QKEY,INTERVIEW_START_W152,INTERVIEW_END_W152,DEVICE_TYPE_W152,SVYMODE_W152,LANG_W152,FORM_W152,AI_HEARD_W152,CNCEXC_W152,USEAI_W152,...,F_PARTYLN_FINAL,F_PARTYSUM_FINAL,F_PARTYSUMIDEO_FINAL,F_REG,F_INC_SDT1,F_IDEO,F_INTFREQ,F_VOLSUM,F_INC_TIER2,WEIGHT_W152
0,100314,15-Aug-2024 15:30:49,15-Aug-2024 15:40:52,1,1,9,1,2,2,5,...,NaN,1,2,1,7,3,3,1,2,0.639769
1,103379,15-Aug-2024 13:58:04,15-Aug-2024 14:21:23,3,1,9,1,2,2,5,...,NaN,1,1,1,9,2,5,2,3,1.338840
2,104727,15-Aug-2024 07:18:22,15-Aug-2024 07:24:47,1,1,9,2,2,3,5,...,NaN,1,1,1,99,2,2,2,99,0.909360
3,106590,13-Aug-2024 22:30:51,13-Aug-2024 22:36:57,1,1,9,1,2,2,5,...,1.0,1,2,1,8,3,2,1,2,0.919896
4,107668,13-Aug-2024 15:23:41,13-Aug-2024 15:30:23,1,1,9,2,2,2,3,...,1.0,1,2,1,9,3,1,1,3,0.719993

In [7]:
for i in data.columns.to_list():
    print(i)

QKEY
INTERVIEW_START_W152
INTERVIEW_END_W152
DEVICE_TYPE_W152
SVYMODE_W152
LANG_W152
FORM_W152
AI_HEARD_W152
CNCEXC_W152
USEAI_W152
AICONTROL1_W152
AICONTROL2_W152
AICHANGE_W152
AIFUTRIMPCT_a_W152
AIFUTRIMPCT_b_W152
AIFUTRIMPCT_c_W152
AIFUTRIMPCT_d_W152
AIFUTRIMPCT_e_W152
AIFUTRIMPCT_f_W152
AIFUTRIMPCT_g_W152
AIFUTRIMPCT_h_W152
AIFUTRIMPCT_i_W152
AIFUTRIMPCT_j_W152
AIJOBS_W152
AIJOBIMPCT_a_W152
AIJOBIMPCT_b_W152
AIJOBIMPCT_c_W152
AIJOBIMPCT_d_W152
AIJOBIMPCT_e_W152
AIJOBIMPCT_f_W152
AIJOBIMPCT_g_W152
AIJOBIMPCT_h_W152
AIJOBIMPCT_i_W152
AIJOBIMPCT_j_W152
HUMANVAI_a_W152
HUMANVAI_b_W152
HUMANVAI_c_W152
HUMANVAI_d_W152
HUMANVAI_e_W152
HUMANVAI_f_W152
HUMANVAI_g_W152
HUMANVAI_h_W152
PERSBENHRM_W152
TRSTAIPRS_W152
AICONCERN_a_W152
AICONCERN_b_W152
AICONCERN_c_W152
AICONCERN_d_W152
AICONCERN_e_W152
AICONCERN_f_W152
AICONCERN_g_W152
FUTRAI_a_W152
FUTRAI_b_W152
FUTRAI_c_W152
FUTRAI_d_W152
DISCRIM1_a_W152
DISCRIM1_b_W152
DISCRIM1_c_W152
DISCRIM1_d_W152
DISCRIM1_e_W152
DISCRIM1_f_W152
AIREG_W152
REGCONFG_W152
REGCONFI_W152
CHATAWARE_W152
CHATUSE_W152
CHATHELPFUL_W152
DRIVE1_W152
DRIVE2_a_W152
DRIVE2_b_W152
DRIVE2_c_W152
DRIVE2_d_W152
DRIVE2_e_W152
DRIVE2_f_W152
DRIVE3_W152
DRIVER_W152
F_METRO
F_CREGION
F_CDIVISION
F_USR_SELFID
F_AGECAT
F_GENDER
F_EDUCCAT
F_EDUCCAT2
F_HISP
F_HISP_ORIGIN
F_YEARSINUS_RECODE
F_RACECMB
F_RACETHNMOD
F_BIRTHPLACE
F_MARITAL
F_RELIG
F_BORN
F_RELIGCAT1
F_ATTENDPER
F_PARTY_FINAL
F_PARTYLN_FINAL
F_PARTYSUM_FINAL
F_PARTYSUMIDEO_FINAL
F_REG
F_INC_SDT1
F_IDEO
F_INTFREQ
F_VOLSUM
F_INC_TIER2
WEIGHT_W152

In [8]:
data.drop_duplicates(inplace=True)
data.dropna(how='all', inplace=True)

In [ ]:
print('Cleaned Features Sample:')
display(data.info())
print('Cleaned Dataset Sample:')
display(data.info())

Cleaned Features Sample:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Columns: 106 entries, QKEY to WEIGHT_W152
dtypes: float64(29), int64(75), object(2)
memory usage: 4.4+ MB

None

Cleaned Dataset Sample:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5410 entries, 0 to 5409
Columns: 106 entries, QKEY to WEIGHT_W152
dtypes: float64(29), int64(75), object(2)
memory usage: 4.4+ MB

None

In [ ]:
exclude_cols = [...]
feature_cols = [col for col in data.columns if col not in exclude_cols]

In [ ]:
X = data[feature_cols]
y = data['...']
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

## new dataset

In [14]:
data = pd.read_csv('data/Spring 2025/Pew Research Center Global Attitudes Spring 2025 Dataset CSV.csv')

/var/folders/4x/24sg3sl162590gg14qfbwf_c0000gn/T/ipykernel_33791/3933118801.py:1: DtypeWarning: Columns (5,11,18,19,20,21,68,69,133,135,137,139,141,143,168,207,208,209,210,211,212,213,214,215,216,217,218,219,220,222,223,224,225,226,283,285,328,360,395,399,409,448,453,462,478,482) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv('data/Spring 2025/Pew Research Center Global Attitudes Spring 2025 Dataset CSV.csv')

In [15]:
display(data.describe())
display(data.head())

,survey,country,weight,id,econ_sit,fav_us,fav_china,fav_eu,fav_un,fav_russia,...,aireg_us,aireg_china,aireg_eu,aireg_country,religion_combined,religion_christian,religion_none,religion_import,pray_freq,trust_people
count,28333.0,28333.000000,28333.000000,2.833300e+04,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000,...,28333.000000,28333.00000,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000,28333.000000
mean,1202501.0,13.753750,1.000000,2.590043e+07,2.798115,2.893869,3.140190,2.830622,2.853845,3.437793,...,3.237003,3.55723,3.285568,2.832386,8.166202,57.175414,80.149966,2.133978,3.858822,1.590760
std,0.0,6.549977,0.758740,1.647632e+07,1.062218,1.599139,1.709583,1.913860,1.898562,1.645220,...,2.056792,2.03534,2.295470,2.060251,21.490274,48.240829,38.288988,1.217162,2.492324,0.911746
min,1202501.0,2.000000,0.060789,4.000000e+00,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.00000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000
25%,1202501.0,9.000000,0.466562,1.508591e+07,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,2.000000,2.00000,2.000000,2.000000,1.000000,2.000000,99.000000,1.000000,1.000000,1.000000
50%,1202501.0,14.000000,0.787611,2.108125e+07,3.000000,3.000000,3.000000,2.000000,2.000000,3.000000,...,3.000000,3.00000,2.000000,2.000000,2.000000,99.000000,99.000000,2.000000,3.000000,2.000000
75%,1202501.0,19.000000,1.289170,4.113238e+07,4.000000,4.000000,4.000000,3.000000,3.000000,4.000000,...,4.000000,4.00000,4.000000,3.000000,7.000000,99.000000,99.000000,3.000000,7.000000,2.000000
max,1202501.0,25.000000,5.892368,5.808552e+07,9.000000,9.000000,9.000000,9.000000,9.000000,9.000000,...,9.000000,9.00000,9.000000,9.000000,99.000000,99.000000,99.000000,9.000000,9.000000,9.000000

,survey,country,weight,id,econ_sit,satisfied_democracy,polsys_satisfied,fav_us,fav_china,fav_eu,...,region_skorea,region_spain,region_sweden,region_turkey,region_uk,urbanicity,qdate_s,qdate_e,intdate_aus,phone_sample
0,1202501,2,0.592005,8001432,2,2,,4,3,2,...,,,,,,,3/23/2025,3/23/2025,,1
1,1202501,2,0.446814,8003472,4,3,,4,4,2,...,,,,,,,3/11/2025,3/11/2025,,1
2,1202501,2,1.120110,8006468,2,1,,3,8,2,...,,,,,,,4/1/2025,4/1/2025,,1
3,1202501,2,0.695317,8006970,2,1,,4,8,1,...,,,,,,,3/10/2025,3/10/2025,,1
4,1202501,2,0.369352,8008601,2,2,,4,3,1,...,,,,,,,3/23/2025,3/23/2025,,1

In [ ]:
data.drop_duplicates(inplace=True)
data.dropna(how='all', inplace=True)

In [16]:
print('Cleaned Features Sample:')
display(data.info())
print('Cleaned Dataset Sample:')
display(data.info())

Cleaned Features Sample:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28333 entries, 0 to 28332
Columns: 483 entries, survey to phone_sample
dtypes: float64(1), int64(63), object(419)
memory usage: 104.4+ MB

None

Cleaned Dataset Sample:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 28333 entries, 0 to 28332
Columns: 483 entries, survey to phone_sample
dtypes: float64(1), int64(63), object(419)
memory usage: 104.4+ MB

None

In [17]:
exclude_cols = [...]
feature_cols = [col for col in data.columns if col not in exclude_cols]

In [ ]:
X = data[feature_cols]
y = data['...']
# Train/test split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)